### PR TITLE
Improve README and fix #19

### LINKED ISSUE #19: EACCES /sys/class/gpio/export
After installing this module and following the README I got this error message:
```
0|mm       | { Error: EACCES: permission denied, open '/sys/class/gpio/export'
0|mm       |     at Error (native)
0|mm       |     at Object.fs.openSync (fs.js:640:18)
0|mm       |     at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
0|mm       |     at Object.fs.writeFileSync (fs.js:1343:33)
0|mm       |     at new Gpio (/home/patrick/MagicMirror/modules/MMM-PIR-Sensor/node_modules/onoff/onoff.js:88:8)
0|mm       |     at Class.socketNotificationReceived (/home/patrick/MagicMirror/modules/MMM-PIR-Sensor/node_helper.js:44:18)
0|mm       |     at Socket.<anonymous> (/home/patrick/MagicMirror/modules/node_modules/node_helper/index.js:98:10)
0|mm       |     at emitTwo (events.js:106:13)
0|mm       |     at Socket.emit (events.js:191:7)
0|mm       |     at /home/patrick/MagicMirror/node_modules/socket.io/lib/socket.js:503:12
0|mm       |   errno: -13,
0|mm       |   code: 'EACCES',
0|mm       |   syscall: 'open',
0|mm       |   path: '/sys/class/gpio/export' }

```

For me, it seems that the README is wrong, because the given command creates a new user gpio with primary group pi. Instead of adding the pi user to gpio group.
`Add your user (pi?) to the gpio group by executing sudo useradd -g pi gpio.`

After realizing, I also added my user to the gpio group by executing `sudo usermod -a -G gpio pi` and it worked. Deleting the previously created user `gpio` (via `sudo userdel -r gpio`) prompts no error message.

### PR DESCRIPTION
**Pull request by Patrick-Remy**

### CODE REVIEW

**Comment by Joshua-Roe** [comment]
'NOPASSWD', is this not a massive security risk?

**Comment by Patrick-Remy** [comment]
It's default for standard pi user, another option would be to pass the password to the module - even more a security risk. But I am open, if you have a more secure option to execute sudo commands with node, without typing password :)

**Comment by Joshua-Roe** [comment]
from: http://the-martins.org/?p=81

> Both “tvservice” and “chvt” need root permissions to work.  So you could use “sudo” or be logged in as root to run those commands, or you can make them suid:
> chmod u+s /opt/vc/bin/tvservice
> chmod u+s /bin/chvt
> Note that suid binaries are generally considered a security risk


its a push but it should work

**Comment by Patrick-Remy** [comment]
That's even better!

**Comment by Patrick-Remy** [comment]
tvservice doesn't requires sudo, also in the code it's not called with sudo, I'll remove that.

**Comment by paviro** [comment]
Is this really safer than using sudo?
```
Note that suid binaries are generally considered a security risk since they run with root permissions.  Often there are ways to use the escalated privileges to run other commands as root.  So only make those binaries suid if you’re in an environment where it would be OK for anyone to have root privileges.
```
http://the-martins.org/?p=81

**Pull request closed without merging**
